name: Terraform lint and plan

# this is the event trigger
on:
   push: 
     branches: ["main"]  ## pipeline should be triggered upon push to the main branch
   pull_request:
     branches: ["main"] ## pipelins should be triggered upon push to main

jobs: ## a series of steps that contains commands to be executed

  terraform-plan: ## name of the job
    runs-on: ubuntu-latest  ## defines the runner where your jobs will execute it steps.The runners could self hosted or github provided once (ubuntu latest, macOS, windows)
    steps:   ## it is a command or action to be ran on the server provided for the job. within a job, the first step must run and complete before must the second step.
      - name: update apt
        run: apt get update -y && get upgrade -y
      - name: say Hello
        run: echo "Hello"
